# Generated by Django 3.1.7 on 2022-10-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20221016_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
    ]
